Update index.js
Final Html can't build because of wrong property/reference

/home/ec2-user/pitometer-ui/index.js:353
            finalHtml = indexhtml.replace("MONGODB", config.mongodb).replace("DYNATRACEURL",dynatraceSecrets.DynatraceUrl).replace("SELFURL", "http://localhost:" + config.port);
                                                                                                              ^
TypeError: Cannot read property 'DynatraceUrl' of undefined
    at Server.<anonymous> (/home/ec2-user/pitometer-ui/index.js:353:111)
    at Server.emit (events.js:193:13)
    at parserOnIncoming (_http_server.js:680:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)